export const availableLanguages = [
    {
        lang: "it",
        label: "Italiano"
    },
    {
        lang: "en",
        label: "English"
    },
]

export default {
    it: {
        login: {
            WELCOME_USER: "Benvenuto su Found!, la piattaforma ideale per programmare al meglio i tuoi viaggi",
            FORGET_PW: "Password Dimenticata?",
            RESET_PW_MESSAGE: "Inserisci il tuo indirizzo email, ti invieremo le istruzioni per resettare la tua password",
            REGISTER: "Non hai ancora un Account?",
            REDIRECT_BUSINESS: "Sei un'azienda?",
            WELCOME_BUSINESS: "Benvenuto su Found!Business, la piattaforma ideale per promuovere la tua impresa",
            TRY: "Prova il nostro",
            NO_BUSINESS: "Non sei un'azienda?",
            HELP: "Hai bisogno di aiuto?",
            CONTACT: "Contattaci",
            SLIDE1_TITLE: "Pubblicizza la tua impresa",
            SLIDE1_TEXT: "Tramite la community potrai raggiungere ogni parte del mondo grazie al passa parola",
            SLIDE2_TITLE: "Promuovi i tuoi eventi",
            SLIDE2_TEXT: "Con Found! Business sarà molto facile pubblicizzare i tuoi eventi",
            SLIDE3_TITLE: "Ricevi i feedback",
            SLIDE3_TEXT: "Ogni utente potrà parlare di te e lasciare una recensione",
        },
        subscription: {
            ACCEPT: "Accetto i",
            TERMS: "Termini & Condizioni",
            LOGIN: "Hai già un account?",
            CONTACT: "Referente",
            PH_COMPANY: "Azienda Srl"
        },
        footer: {
            TERMS: "Condizioni d'uso",
            PRIVACY: "Informativa sulla Privacy",
            HELP: "Aiuto",
            COOKIES: "Informativa sui Cookie"
        },        
        menu: {
            TITLE_1: "Principale",
            TITLE_2: "Strumenti",
        },
        globals: {
            FEED: "Bacheca",
            PROFILE: "Profilo",
            GROUPS: "Gruppi",
            CHAT: "Chat",
            CALENDAR: "Calendario",
            FAVORITES: "Preferiti",
            EMAIL: "Indirizzo Email",
            PH_EMAIL: "Inserisci Email",
            NAME: "Nome",
            SURNAME: "Cognome",
            PW_CONFIRM: "Conferma Password",
            COMPANY_NAME: "Ragione Sociale",
            VAT_NUMBER: "Partita IVA",
        },
        profile: {
            EDIT_P: "Modifica Profilo",
            SETTING: "Impostazioni",
            EVENTS: "Eventi",
            FOLLOWING: "Seguiti",
            PLACES: "Luoghi",
            VISITED: "Luoghi Visitati",
            EVENTS_: "Eventi in Programma",
            SUGG_EVENTS: "Eventi Suggeriti",
            SUGG_ACCOUNT: "Account Suggeriti",
            REVIEWS: "Recensioni",
            UNLOCK: "Sblocca Utente",
            BLOCK: "Blocca Utente",
            FOLLOW: "Segui",
            UNFOLLOW: "Non seguire più",
            MESSAGE: "Messaggio",
            UNLOCK_USER: "Sblocca questo utente per vedere i suoi contenuti",
            NO_REV: "Recensioni non trovate",
        },
        editProfile: {
            PERSONAL: "Informazioni Personali",
            IMAGE: "Modifica Immagine Profilo",
            CHANGE: "Cambia Password",
            NICKNAME:"Gestisci Nickname",
            CONTACT: "Gestisci Contatti",
            EDIT: "Modifica",
            PHONE: "Numero di Telefono",
            BIRTHDAY: "Data di Nascita",
            COUNTRY: "Nazione",
            CITY: "Città",
            BIO: "Biografia",
            CURRENT_PW: "Password Attuale",
            NEW_PW: "Nuova Password",
        },
        settings: {
            TITLE_ACCOUNT: "Impostazioni Account",
            LANGUAGE: "Lingua",
            THEME: "Tema",
            NOTIFICATIONS: "Notifiche",
            DEVICE_AUTHORIZATION: "Autorizzazioni Dispositivo",
            BLOCKED: "Utenti Bloccati",
            NO_BLOCKED: "Nessun Utente Bloccato",
            SERVICE: "Assistenza",
            TICKET: "Ticket Aperti",
            DELETE: "Elimina Account",
            SURE: "Sei sicuro di voler eliminare l'account?",
            TITLE_SOCIAL: "Altri Social",
            CAMERA: "Fotocamera",
        },
        tickets: {
            DESCRIPTION: "Descrizione",
            DATE: "Data",
            TYPE: "Categoria",
            STATUS: "Stato",
            PROBLEM: "Descrivi il Problema",
            NEW_TITLE: "Inserimento Nuovo Ticket",
            NEW: "Nuovo Ticket",
        },
        btn: {
            SEND: "Invia",
            SAVE: "Salva",
            ADD: "Aggiungi",
            CREATE: "Crea",
            LOGIN: "Accedi",
            LOGOUT: "Esci",
            SUBSCRIBE: "Iscriviti",
            COMMENT: "Commenta",
            DELETE: "Elimina",
            CANCEL: "Annulla",
            REVIEW: "Nuova Recensione",
            BACK: "Indietro" 
        },
        calendar: {
            TITLE: "Titolo",
            START: "Inizio",
            END: "Fine",
            DESCRIPTION: "Descrizione",
            TIME: "Orario"
        },
        chat: {
            FIND: "Cerca Chat...",
            WITH: "Chat con",
            START: "Inizia a Chattare",
            CLEAN: "Svuota",
            CLEAN_CHAT: "Svuota la Chat",
            REPORT: "Segnala e Blocca",
            REPORT_ACC: "Segnala e blocca l'utente",
            DELETE: "Eminina Chat",
            DELETE_CHAT: "Elimina definitivamente la chat"
        },
        postEditing: {
            ADD: "Aggiungi un post",
            TYPE: "Tipologia",
            BASIC: "Base",
            EVENT: "Evento",
            PLACE: "Dove ti trovavi?",
            PHOTO: "Aggiungi Foto",
            VIDEO: "Aggiungi Video",
            ADD_PLACE: "Aggiungi Luogo"
        },
        review: {
            NEW: "Nuova Recensione",
            ADD: "Aggiungi Recensione",
            RATING: "Valutazione",
            REVIEW: "Recensione",
            PH_RREVIEW: "La tua recensione...",
        },
        customBox: {
            EDIT: "Modifica Post",
            DELETE: "Elimina Post",
            HIDE: "Nascondi Post",
            SHOW: "Mostra meno post come questo",
            UNFOLLOW: "Non vedrai più i post di questo utente",
            NOTIFICATIONS: "Attiva Notifiche",
            MORE: "Riceverai notifiche per i nuovi post di questo utente.",
            SHARE: "Condividi",
            COPY: "Copia",
            LIKES: "e altri 99 hanno messo Mi Piace",
            N_LIKES: "100 Mi Piace",
            N_COMMENTS: "20 Commenti",
            TIME: "2 Minuti fa",
            REACTIONS: "Reazioni",
            REPLY: "Rispondi...", 
            ADD_COMMENT: "Aggiungi un commento...",
            SEND: "Invia a...",
            CREATE_EVENT: "Crea Evento"
        },
        success: {
            IMAGE: "Immagine Profilo Caricata",
            PROFILE: "Informazioni del Profilo Aggiornate",
            PASSWORD: "Password Aggiornata",
            EMAIL: "Email Aggiornata",
            NICKNAME: "Nickname Aggiornato",
            NEW_ACCOUNT: "Utente registrato con successo, puoi accedere al tuo nuovo account!",
            POST: "Post creato",
            REVIEW: "Recensione Inviata",
            EVENT: "Evento aggiunto al calendario",
            FAVORITES: "Post aggiunto ai preferiti"
        },
        errors: {
            WRONG: "Ops! Qualcosa è andato storto.",
            PW_WRONG: "Le Password non corrispondono.",
            SERVER: "Errore Interno del Server",
        },
    },
    en: {
        login: {
            WELCOME_USER: "Welcome to Found!, a perfect social to plan your trips better!",
            FORGET_PW: "Forgotten password?",
            RESET_PW_MESSAGE: "Enter your email address, we will send you instructions to reset your password",
            REGISTER: "Don't have an account yet?",
            REDIRECT_BUSINESS: "Are you a company?",
            WELCOME_BUSINESS: "Welcome to Found!Business, a perfect social  to promote your business",
            TRY: "Try our",
            NO_BUSINESS: "Not a Company?",
            HELP: "Do you need help?",
            CONTACT: "Contact us",
            SLIDE1_TITLE: "Promote yor business!",
            SLIDE1_TEXT: "Through the community you can reach every part of the world thanks to word of mouth",
            SLIDE2_TITLE: "Promote your events",
            SLIDE2_TEXT: "With Found! Business it will be easier to promote your events",
            SLIDE3_TITLE: "Get feedbacks",
            SLIDE3_TEXT: "Every user can talk about you and leave a review",
        },
        subscription: {
            ACCEPT: "I Accept",
            TERMS: "Terms & Condtions",
            LOGIN: "Already have an account?",
            CONTACT: "Contact Person",
            PH_COMPANY: "Company Srl"
        },
        footer: {
            TERMS: "Terms of use",
            PRIVACY: "Privacy Statement",
            HELP: "Help",
            COOKIES: "Information on Cookies"
        },
        menu: {
            TITLE_1: "Main",
            TITLE_2: "Tools",     
        },
        globals: {
            FEED: "Feed",
            PROFILE: "Profile",
            GROUPS: "Groups",
            CHAT: "Chat",
            CALENDAR: "Calendar",
            FAVORITES: "Favorites",
            PH_EMAIL: "Enter Email",
            EMAIL: "Email Address",
            NAME: "Name",
            SURNAME: "Surname",
            PW_CONFIRM: "Confirm Password",
            COMPANY_NAME: "Company Name",
            VAT_NUMBER: "VAT Number",
        },
        profile: {
            EDIT_P: "Edit Profile",
            SETTING: "Settings",
            EVENTS: "Events",
            FOLLOWING: "Following",
            PLACES: "Places",
            VISITED: "Visited Places",
            EVENTS_: "Scheduled Events.",
            SUGG_EVENTS: "Recommended Events",
            SUGG_ACCOUNT: "Recommended Accounts",
            REVIEWS: "Review",
            UNLOCK: "Unlock User",
            BLOCK: "Block User",
            FOLLOW: "Follow",
            UNFOLLOW: "Unfollow",
            MESSAGE: "Chat",
            UNLOCK_USER: "Unblock this user to see their content",
            NO_REV: "No Reviews",
        },
        editProfile: {
            PERSONAL: "Personal Information",
            IMAGE: "Change Profile Picture",
            CHANGE: "Change Password",
            NICKNAME:"Manage Nickname",
            CONTACT: "Manage Contact",
            EDIT: "Edit",
            PHONE: "Phone Number",
            BIRTHDAY: "Date of birth",
            COUNTRY: "Country",
            CITY: "City",
            BIO: "About me",
            CURRENT_PW: "Current Password",
            NEW_PW: "New Password",
        },
        settings: {
            TITLE_ACCOUNT: "Account Settings",
            LANGUAGE: "Languages",
            THEME: "Theme",
            NOTIFICATIONS: "Notifications",
            DEVICE_AUTHORIZATION: "Device Authorization",
            BLOCKED: "Blocked Users",
            NO_BLOCKED: "No Blocked User",
            SERVICE: "Customer Service",
            TICKET: "Open Tickets",
            DELETE: "Delete Account",
            SURE: "Are you sure to delete the Account?",
            TITLE_SOCIAL: "Other Socials",
            CAMERA: "Camera",
        },
        tickets: {
            DESCRIPTION: "Description",
            DATE: "Date",
            TYPE: "Type",
            STATUS: "Status",
            PROBLEM: "Enter a description of the problem.",
            NEW_TITLE: "New Ticket Page",
            NEW: "New Ticket",
        },
        btn: {
            SEND: "Send",
            SAVE: "Save",
            ADD: "Add",
            CREATE: "Create",
            LOGIN: "Login",
            LOGOUT: "Logout",
            SUBSCRIBE: "Subscribe",
            COMMENT: "Comment",
            DELETE: "Delete",
            CANCEL: "Cancel" ,
            REVIEW: "New Review",
            BACK: "Back"
        },
        calendar: {
            TITLE: "Title",
            START: "Start",
            END: "End",
            DESCRIPTION: "Description",
            TIME: "Time"
        },
        chat: {
            FIND: "Search Chat...",
            WITH: "Chat with",
            START: "Start a Conversation",
            CLEAN: "Clean",
            CLEAN_CHAT: "Clean the Chat",
            REPORT: "Report e Block",
            REPORT_ACC: "Report e block this Account",
            DELETE: "Delete Chat",
            DELETE_CHAT: "Permanently delete the chat"
        },
        postEditing: {
            ADD: "Create new Post",
            TYPE: "Type",
            BASIC: "Basic",
            EVENT: "Event",
            PLACE: "Where were you?",
            PHOTO: "Upload Picture",
            VIDEO: "Upload Video",
            ADD_PLACE: "Add Place"
        },
        review: {
            NEW: "New Review",
            ADD: "Add a review",
            RATING: "Rating",
            REVIEW: "Review",
            PH_RREVIEW: "Your review...",
        },
        customBox: {
            EDIT: "Edit Post",
            DELETE: "Delete Post",
            HIDE: "Hide Post",
            SHOW: "Show less post like this",
            UNFOLLOW: "You no longer see this User Posts",
            NOTIFICATIONS: "Turn on Notifications",
            MORE: "You will receive notifications for every new posts from this user.",
            SHARE: "Share",
            COPY: "Copy",
            LIKES: "and 99 others Liked It",
            N_LIKES: "100 Likes",
            N_COMMENTS: "20 Comments",
            TIME: "2 Minuts ago",
            REACTIONS: "Reactions",
            REPLY: "Reply", 
            ADD_COMMENT: "Add a comment...",
            SEND: "Send to...",
            CREATE_EVENT: "New Event"
        },
        success: {
            IMAGE: "Profile Image Updated",
            PROFILE: "Profile Informations Updated",
            PASSWORD: "Password Updated",
            EMAIL: "Email Updated",
            NICKNAME: "Nickname Updated",
            NEW_ACCOUNT: "User successful subscribed, you can log now!",
            POST: "Post created",
            REVIEW: "Review Submitted",
            EVENT: "Added event to calendar",
            FAVORITES: "Added post to favorites"
        },
        errors: {
            WRONG: "Something Went Wrog",
            PW_WRONG: "Passwords don't match",
            SERVER: "Internal Server Error",

        },
    }
}